---
title: "esm 206 assignment 4"
author: "Derek Nguyen and Bobby Miyashiro"
date: "11/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE, eval = FALSE}
install.packages("directlabels")
install.packages("viridis")
install.packages("lmtest", repos = "http://cran.us.r-project.org")
```


```{r}
library(tidyverse)
library(janitor)
library(tidyr)
library(ggridges)
library(directlabels)
library(lattice)
library(viridis)
```

###INTRODUCTION

###DATA AND METHODS


###RESULTS




```{r}
lobster_abundance <- read_csv("lobster_abundance_sbc_lter.csv",
                              na = "-99999") %>% 
  clean_names() 
```

```{r}
lobster_tidy <- lobster_abundance %>% 
  tidyr::uncount(count)
```



```{r}
lobster_ysite <- lobster_tidy %>% 
  select(year, site, size_mm) %>% 
  count(year, site) %>%  
  group_by(site, year) %>% 
  mutate(MPA = case_when(
    site %in% c("IVEE", "NAPL") ~ "MPA",
    site %in% c("AQUE", "MOHK", "CARP") ~ "non-MPA"))

```

```{r}
colnames(lobster_ysite)[colnames(lobster_ysite) =="n"] <- "total_count"

lobster_ysite$site[lobster_ysite$site == "AQUE"] <- "Arroyo Quemado"

lobster_ysite$site[lobster_ysite$site == "CARP"] <- "Carpinteria"

lobster_ysite$site[lobster_ysite$site == "IVEE"] <- "Isla Vista"

lobster_ysite$site[lobster_ysite$site == "MOHK"] <- "Mohawk"

lobster_ysite$site[lobster_ysite$site == "NAPL"] <- "Naples"
```

#Results A: Visually explore changes in annual lobster abundance (counts) by site
```{r}
ggplot(lobster_ysite, aes(x = year, y = total_count),
       show.legend = FALSE) +
  geom_line(aes(color = MPA),
            show.legend = FALSE) +
  facet_wrap(~site) +
  geom_point(aes(color = MPA, shape = MPA)) +
  scale_x_continuous(lim = c(2012, 2021), expand = c(0,0)) +
  scale_y_continuous(lim = c(0, 1000), expand = c(0,0)) +
  theme_minimal() +
  labs(title = "Annual Lobster Abundance by Site, 2012 - 2018",
       subtitle = "MPAs: IVEE & NAPL",
       x = "Year",
       y = "Total Lobster Observations",
       caption = "Figure 1: Lobster Abundance at 5 sites for year 2012 - 2018")  +
  geom_dl(aes(label = site, color = MPA), method = list("last.points", cex = .65, hjust = -.10))
            
```
 
```{r}
ggplot(lobster_ysite, aes(x = year, y = total_count),
       show.legend = FALSE) +
  geom_line(aes(color = site),
            show.legend = FALSE) +
  geom_point(aes(color = site, shape = site),
             show.legend = FALSE) +
  scale_x_continuous(lim = c(2012, 2019), expand = c(0,0)) +
  scale_y_continuous(lim = c(0, 1000), expand = c(0,0)) +
  theme_minimal() +
  labs(title = "Annual Lobster Abundance by Site, 2012 - 2018",
       subtitle = "MPAs: IVEE & NAPL",
       x = "Year",
       y = "Total Lobster Observations",
       caption = "Figure 1: Lobster Abundance at 5 sites for year 2012 - 2018")  +
  geom_dl(aes(label = site, color = site), method = list("last.points", cex = .65, hjust = -.2))
```
 
 


```{r}
ggplot(lobster_ysite, aes(x = year, y = total_count, fill = site)) +
  geom_col(aes(fill = MPA, color = MPA, alpha = 0.7), 
           show.legend = FALSE) +
  facet_wrap(~site) +
  theme_minimal() +
  scale_y_continuous(expand = c(0,0), lim = c(0,1000)) +
  scale_x_continuous(expand = c(0,0)) +
  labs(title = "Annual Lobster Abundance by Site, 2012 - 2018",
       subtitle = "MPAs: Isla Vista and Naples",
       x = "Year",
       y = "Total Lobster Observations",
       caption = "Figure 1: Lobster Abundance at 5 sites for year 2012 - 2018")
```


Results B. Visually explore lobster size distribution shifts by comparing lobster sizes in 2012 and 2018.

```{r}
lobster_size <- lobster_tidy %>% 
  filter(year %in% c(2012, 2018)) %>% 
  select(year, site, size_mm)

lobster_size$site[lobster_size$site == "AQUE"] <- "Arroyo Quemado"

lobster_size$site[lobster_size$site == "CARP"] <- "Carpinteria"

lobster_size$site[lobster_size$site == "IVEE"] <- "Isla Vista"

lobster_size$site[lobster_size$site == "MOHK"] <- "Mohawk"

lobster_size$site[lobster_size$site == "NAPL"] <- "Naples"
```

Histogram for Results B
```{r}
ggplot(data = lobster_size) +
  geom_histogram(aes(x = size_mm, fill = site, alpha = 0.7, color = site),
                 show.legend = FALSE) +
  facet_grid(year~site, scales = "free") +
  theme_bw() +
  scale_y_continuous(expand = c(0,0)) +
  scale_x_continuous(expand = c(0,0)) +
  labs(title = "Lobster Size Distributions across 5 Sites",
       caption = "Figure 2: Lobster Size for 2012 & 2018",
       subtitle = "2012 & 2018",
       x = "Lobster Size (mm)",
       y = "Total Lobster Observations")
```

```{r}
ggplot(data = lobster_size) +
  geom_qq(aes(sample = size_mm, color = site, alpha = 0.5, fill = site),
      shape = 25,
          show.legend = FALSE) +
  facet_grid(year~site, scales = "free") +
  theme_minimal()
  
```



Results C. Compare mean lobster sizes at MPA vs. non-MPA sites in 2012 and 2018. 

```{r}
lobster_mean_size <- lobster_tidy %>% 
  mutate(mpa = case_when(
    site %in% c("IVEE", "NAPL") ~ "MPA",
    site %in% c("AQUE", "MOHK", "CARP") ~ "non-MPA")) %>% 
  filter(year %in% c(2012, 2018)) %>% 
  select(year, site, size_mm, mpa) %>% 
  group_by(year, mpa)
```

```{r}
nonmpa_2012 <- lobster_mean_size %>% 
  filter(year =="2012", mpa == "non-MPA") 

nonmpa_2018 <- lobster_mean_size %>% 
  filter(year == "2018", mpa == "non-MPA")

mpa_2012 <- lobster_mean_size %>% 
  filter(year == "2012", mpa == "MPA")

mpa_2018 <- lobster_mean_size %>% 
  filter(year == "2018", mpa == "MPA")





mean_mpa_2012 <- mean(mpa_2012$size_mm, na.rm = TRUE) 
mean_mpa_2018 <- mean(mpa_2018$size_mm, na.rm = TRUE) 
mean_nonmpa_2012 <- mean(nonmpa_2012$size_mm, na.rm = TRUE)
mean_nonmpa_2018 <- mean(nonmpa_2012$size_mm, na.rm = TRUE)

sd_mpa_2012 <- sd(mpa_2012$size_mm, na.rm = TRUE)
sd_mpa_2018 <- sd(mpa_2018$size_mm, na.rm = TRUE)
sd_nonmpa_2012 <- sd(nonmpa_2012$size_mm, na.rm = TRUE)
sd_nonmpa_2018 <- sd(nonmpa_2018$size_mm, na.rm = TRUE)






  
```









SUMMARY

-testing

REFERENCES